let formatButton = document.querySelector(".toggle-format-btn");
let is12Hours = true;
formatButton.textContent = "Switch to 24h";

formatButton.addEventListener("click", () => {
  is12Hours = !is12Hours;
  formatButton.textContent = is12Hours ? "Switch to 24h" : "Switch to 12h";
  getTime();
});

function getTime() {
  const today = new Date();
  let hours = today.getHours();
  const AmPm = hours >= 12 ? "PM" : "AM";

  if (is12Hours) {
    hours = hours % 12 || 12;
  }
  hours = String(hours).padStart(2, "0");

  const minutes = String(today.getMinutes()).padStart(2, "0");
  const seconds = String(today.getSeconds()).padStart(2, "0");

  document.querySelector(".clock").textContent = is12Hours
    ? `${hours}:${minutes}:${seconds} ${AmPm}`
    : `${hours}:${minutes}:${seconds}`;

  const msUntilNextSecond = 1000 - today.getMilliseconds(); // ← generated by ChatGPT
  setTimeout(getTime, msUntilNextSecond); // ← generated by ChatGPT
}
getTime();
